spring:
  datasource:
    url: jdbc:mysql://localhost:3306/socketSpringBoot
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update

  application:
    name: inventarioInicial


server:
  port: 8081

